target:
  url: https://www.baidu.com
#spring:
#  datasource:
#    url: jdbc:mysql://10.50.115.114:16052/mysql?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
#    username: mama100
#    password: Dd23FfASdfDF
#    driver-class-name: com.mysql.jdbc.Driver